# Generated by Django 2.2 on 2019-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190428_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_off',
            field=models.CharField(max_length=20),
        ),
    ]
